//user info
export const SET_BASEINFO = 'SET_BASEINFO'
export const GET_BASEINFO = 'GET_BASEINFO'
export const COMMEN_ROLE = 'COMMEN_ROLE'
export const CLEAR_BASEINFO = 'CLEAR_BASEINFO'
export const GET_BGCOLOR = 'GET_BGCOLOR'
export const GET_FONTCOLOR = 'GET_FONTCOLOR'
export const GET_BORDERCOLOR = 'GET_BORDERCOLOR'
export const GET_ACTIVECOLOR = 'GET_ACTIVECOLOR'
export const EXCHANGE_ROLE = 'EXCHANGE_ROLE'

//tabbar
export const TABBAR_SHOW_STATUS = 'TABBAR_SHOW_STATUS'

//toast
export const TOAST_SHOW_STATUS = 'TOAST_SHOW_STATUS'

//countdown
export const START_COUNTDOWN = 'START_COUNTDOWN'

//shopping_car
export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const DELETE_ITEM = 'DELETE_ITEM'
export const CHANGE_ONE_QUANTITY = 'CHANGE_ONE_QUANTITY'
